# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Tf_DockerReg'
        repository: 'rnagelli/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  displayName: Terraform on Azure
  dependsOn: Build
  jobs:
    - job: Provision
      displayName: Provisioning Container Instance
      pool:
        vmImage: ubuntu-latest
      variables:
      - group: terraformenvvars
      steps:
      - script: 
          set -e 
          terraform init -input=false
          terraform apply -input=false -auto-approve
        name: 'RunTerraform'
        displayName: 'RunTerraform' 
        env:
          subscription_id : $(subscription_id)
          tenant_id     : $(tenant_id)
          client_id     : $(client_id)
          client_secret : $(client_secret)